# Generated by Django 5.2.15 on 2026-07-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='✓', max_length=10, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('source', models.CharField(blank=True, default='сайт', max_length=100, verbose_name='Источник')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('rejected', 'Отказ')], default='new', max_length=20, verbose_name='Статус')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Внутренние заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(choices=[('gates', 'Ворота'), ('barriers', 'Шлагбаумы'), ('doors', 'Гаражные двери'), ('repair', 'Ремонт')], max_length=20, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Фото')),
                ('image_before', models.ImageField(blank=True, null=True, upload_to='portfolio/before/', verbose_name='Фото до (ремонт)')),
                ('image_after', models.ImageField(blank=True, null=True, upload_to='portfolio/after/', verbose_name='Фото после (ремонт)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Пример работы',
                'verbose_name_plural': 'Примеры работ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('category', models.CharField(choices=[('gates', 'Ворота и роллеты'), ('install', 'Монтаж и наладка'), ('service', 'Обслуживание и ремонт'), ('barriers', 'Шлагбаумы'), ('doors', 'Гаражные двери')], max_length=20, verbose_name='Категория')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('options', models.TextField(blank=True, help_text='Каждая опция с новой строки', verbose_name='Опции (по строке)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Изображение')),
                ('icon', models.CharField(default='🚪', max_length=10, verbose_name='Иконка (emoji)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('show_on_home', models.BooleanField(default=False, verbose_name='Показывать на главной')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ВоротаПро', max_length=200, verbose_name='Название компании')),
                ('tagline', models.CharField(default='Современные ворота и автоматика под ключ', max_length=300, verbose_name='Слоган')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Логотип')),
                ('hero_title', models.CharField(default='Современные ворота и автоматика под ключ — от установки до управления со смартфона', max_length=300, verbose_name='Заголовок главной')),
                ('hero_subtitle', models.TextField(default='Продаём, монтируем, налаживаем и обслуживаем ворота и роллеты всех видов', verbose_name='Подзаголовок главной')),
                ('phone', models.CharField(default='+7 (999) 123-45-67', max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(default='info@vorota-pro.ru', max_length=254, verbose_name='Email')),
                ('address', models.CharField(default='г. Москва, ул. Примерная, д. 1', max_length=300, verbose_name='Адрес')),
                ('map_embed_url', models.URLField(blank=True, default='https://yandex.ru/map-widget/v1/?um=constructor%3Aexample&amp;source=constructor', verbose_name='URL карты (iframe)')),
                ('whatsapp', models.CharField(blank=True, default='79991234567', max_length=30, verbose_name='WhatsApp')),
                ('telegram', models.CharField(blank=True, default='vorotapro', max_length=50, verbose_name='Telegram')),
                ('footer_description', models.TextField(default='Продажа, монтаж и обслуживание ворот, роллет, шлагбаумов и гаражных дверей. Официальный дилер DoorHan и BFT.', verbose_name='Описание в подвале')),
                ('working_hours', models.CharField(default='Пн–Сб: 9:00–19:00', max_length=100, verbose_name='Часы работы')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='WorkStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='Номер шага')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Шаг работы',
                'verbose_name_plural': 'Как мы работаем',
                'ordering': ['order'],
            },
        ),
    ]
