# Generated by Django 5.2.15 on 2026-07-07 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(default='📁', max_length=10, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='В меню')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Раздел каталога',
                'verbose_name_plural': 'Разделы каталога',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=300, unique=True, verbose_name='Полный URL-путь')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('page_type', models.CharField(choices=[('overview', 'Обзор'), ('page', 'Страница'), ('product', 'Товар'), ('service', 'Услуга'), ('article', 'Статья')], default='page', max_length=20, verbose_name='Тип')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое (Markdown)')),
                ('excerpt', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Производитель')),
                ('model', models.CharField(blank=True, max_length=200, verbose_name='Модель')),
                ('availability', models.CharField(blank=True, max_length=100, verbose_name='Наличие')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/', verbose_name='Изображение')),
                ('external_image_url', models.URLField(blank=True, max_length=500, verbose_name='Внешнее изображение')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='В меню')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.contentpage', verbose_name='Родитель')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='api.contentsection', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Страница каталога',
                'verbose_name_plural': 'Страницы каталога',
                'ordering': ['order', 'title'],
            },
        ),
    ]
