# Generated by Django 5.2.15 on 2026-07-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contentsection_contentpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('visit_date', models.DateField(verbose_name='Дата визита')),
                ('visited_at', models.DateTimeField(auto_now_add=True, verbose_name='Время визита')),
                ('path', models.CharField(blank=True, default='/', max_length=300, verbose_name='Страница')),
                ('referer', models.CharField(blank=True, max_length=500, verbose_name='Реферер')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'ordering': ['-visited_at'],
                'constraints': [models.UniqueConstraint(fields=('ip_address', 'visit_date'), name='unique_visit_per_ip_per_day')],
            },
        ),
    ]
