# Generated by Django 5.2.15 on 2026-07-08 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sitevisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog_gallery/', verbose_name='Изображение')),
                ('external_image_url', models.URLField(blank=True, max_length=500, verbose_name='Внешнее изображение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='api.contentpage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Изображения галереи',
                'ordering': ['order', 'id'],
            },
        ),
    ]
