# Generated by Django 5.2.15 on 2026-07-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contentpageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Текст сниппета в поисковой выдаче. Рекомендуется 150–160 символов. Если пусто — используется «Краткое описание».', max_length=200, verbose_name='SEO: описание (meta description)'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Рекомендуется 50–60 символов. Если пусто — используется «Заголовок».', max_length=70, verbose_name='SEO: заголовок (title)'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Текст сниппета в поисковой выдаче. Рекомендуется 150–160 символов. Если пусто — используется описание в подвале.', max_length=200, verbose_name='SEO: описание главной (meta description)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Показывается во вкладке браузера и в выдаче поисковиков. Рекомендуется 50–60 символов. Если пусто — используется слоган.', max_length=70, verbose_name='SEO: заголовок главной (title)'),
        ),
    ]
