# Generated by Django 5.2.15 on 2026-07-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contentpage_meta_description_contentpage_meta_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='г. Минск, ул. Брестская, 2, каб. 205', max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='ВоротаРБ', max_length=200, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='vorotarb@mail.ru', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+375 (29) 888-06-88', max_length=30, verbose_name='Телефон'),
        ),
    ]
