# Generated by Django 5.2.16 on 2026-07-08 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sitesettings_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения'),
        ),
    ]
