# Generated by Django 5.2.15 on 2026-07-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_contentpage_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Measurement ID вида G-XXXXXXXXXX из analytics.google.com. Если пусто, аналитика не подключается.', max_length=20, verbose_name='ID Google Analytics (GA4)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_metrika_id',
            field=models.CharField(blank=True, help_text='Только номер счётчика (например, 12345678) — из metrika.yandex.ru. Если пусто, счётчик не подключается.', max_length=20, verbose_name='ID счётчика Яндекс.Метрики'),
        ),
    ]
