# Generated by Django 5.2.15 on 2026-07-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sitesettings_google_analytics_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='page_type',
            field=models.CharField(choices=[('overview', 'Обзор'), ('page', 'Страница'), ('product', 'Товар'), ('service', 'Услуга'), ('article', 'Статья'), ('news', 'Новости (лента)'), ('promotions', 'Акции (лента)'), ('testimonials', 'Отзывы (карточки)')], default='page', max_length=20, verbose_name='Тип'),
        ),
    ]
