# Generated by Django 5.2.15 on 2026-07-08 14:42

from django.db import migrations, models

OLD_PLACEHOLDER = 'https://yandex.ru/map-widget/v1/?um=constructor%3Aexample&amp;source=constructor'


def clear_placeholder_map_url(apps, schema_editor):
    # map_embed_url раньше был обязательным полем с нерабочей заглушкой по
    # умолчанию ("constructor:example") — она никогда не показывала
    # реальную карту. Теперь пустое значение означает "строить карту по
    # адресу автоматически" (см. api.map_utils), поэтому у существующих
    # записей, где стоит именно эта заглушка (а не осознанно введённая
    # админом ссылка), её нужно сбросить в пустую строку.
    SiteSettings = apps.get_model('api', 'SiteSettings')
    SiteSettings.objects.filter(map_embed_url=OLD_PLACEHOLDER).update(map_embed_url='')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_heroslide_image_alter_portfolioitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Если пусто — карта строится автоматически по адресу выше.', verbose_name='Своя ссылка на карту (необязательно)'),
        ),
        migrations.RunPython(clear_placeholder_map_url, migrations.RunPython.noop),
    ]
