# Generated by Django 5.2.15 on 2026-07-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sitesettings_map_yandex_org_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Необязательно. Короткие ссылки maps/-/... не используются — укажите ID организации ниже. Можно вставить готовый embed: yandex.ru/map-widget/v1/...', verbose_name='Ссылка на карту (необязательно)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='WhatsApp'),
        ),
    ]
