# Generated by Django 5.2.15 on 2026-07-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_sitesettings_clear_messenger_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advantages/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_badge',
            field=models.CharField(blank=True, default='Официальный дилер DoorHan, BFT', help_text='Короткая строка над H1 на первом экране. Если пусто — бейдж не показывается.', max_length=120, verbose_name='Бейдж над заголовком главной'),
        ),
    ]
