# Generated by Django 5.2.15 on 2026-07-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_hero_badge_and_advantage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='lead',
            name='drive_type',
            field=models.CharField(blank=True, choices=[('electric', 'С электроприводом'), ('manual', 'Ручные'), ('unknown', 'Пока не знаю')], max_length=20, verbose_name='Тип привода'),
        ),
        migrations.AddField(
            model_name='lead',
            name='interest',
            field=models.CharField(blank=True, max_length=200, verbose_name='Интерес / услуга'),
        ),
        migrations.AddField(
            model_name='lead',
            name='opening_height',
            field=models.CharField(blank=True, max_length=40, verbose_name='Высота проёма'),
        ),
        migrations.AddField(
            model_name='lead',
            name='opening_width',
            field=models.CharField(blank=True, max_length=40, verbose_name='Ширина проёма'),
        ),
    ]
