# Generated by Django 5.2.15 on 2026-07-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_lead_optional_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='privacy_consent',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку ПДн'),
        ),
        migrations.AddField(
            model_name='lead',
            name='privacy_consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время согласия на ПДн'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='consent_checkbox_label',
            field=models.CharField(blank=True, help_text='Краткая формулировка рядом с галочкой. По Закону № 99-З галочка не ставится заранее.', max_length=500, verbose_name='Текст чекбокса согласия в форме'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cookie_policy',
            field=models.TextField(blank=True, verbose_name='Политика cookie'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cookie_updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата обновления политики cookie'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_extra',
            field=models.TextField(blank=True, help_text='Строка под © … вроде «копирование только после согласования».', verbose_name='Доп. текст об авторских правах'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal_entity_name',
            field=models.CharField(blank=True, default='ООО «ВоротаРБ»', help_text='Как в футере и документах: ООО «…». Если пусто — используется название компании.', max_length=300, verbose_name='Юридическое наименование'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_disclaimer',
            field=models.TextField(blank=True, help_text='Общий текст со звёздочкой внизу сайта (не публичная оферта, цены ориентировочные).', verbose_name='Дисклеймер о ценах / оферте'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy',
            field=models.TextField(blank=True, verbose_name='Политика конфиденциальности'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата обновления политики'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_of_use',
            field=models.TextField(blank=True, verbose_name='Пользовательское соглашение'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата обновления соглашения'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='unp',
            field=models.CharField(blank=True, help_text='Учётный номер плательщика. Показывается в подвале сайта.', max_length=20, verbose_name='УНП'),
        ),
    ]
