# Generated by Django 5.2.15 on 2026-07-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_legal_info_and_lead_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Например BY61ALFA…', max_length=34, verbose_name='Расчётный счёт (IBAN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес банка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_bic',
            field=models.CharField(blank=True, max_length=20, verbose_name='BIC / БИК банка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Банк'),
        ),
    ]
